version: '3'
services:
  devbox:
    build:
      context: ./dockerfile-cont
      dockerfile: AvocadoNCWebServer.DockerFile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html/app
  devmysql:
    build:
      context: ./dockerfile-cont
      dockerfile: AvocadoNCMySQL.DockerFile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'VirtualAppliance0952'
      MYSQL_ALLOW_EMPTY_PASSWORD : 'no'
      MYSQL_USER: AvocadoNC
      MYSQL_PASSWORD: AvocadoNC
    restart: always
    volumes:
            #- container-volume:/var/lib/mysql
            - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql        
